version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: minsit-app
    restart: always
    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5433
      DB_DATABASE: minsit_db
      DB_USERNAME: hguerrero
      DB_PASSWORD: password123
      REDIS_HOST: redis
      REDIS_PORT: 6380
      REDIS_DB: 0
      REDIS_CACHE_DB: 0
      FILESYSTEM_DISK: minio
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9002
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: minsit-bucket
    ports:
      - "9010:9000"
    volumes:
      - .:/var/www
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres:17-alpine
    container_name: minsit-db
    restart: always
    environment:
      POSTGRES_DB: minsit_db
      POSTGRES_USER: hguerrero
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: minsit-redis
    restart: always
    ports:
      - "6380:6379"

  minio:
    image: minio/minio:latest
    container_name: minsit-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9002:9000"
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  pgdata:
  minio_data:
